module.exports = {
  title: "seokulee",
  description: "Hello :) I'm Seokkyu. I'm studying data engineering and data science. I'm also interested in web development.",
  author: "seokulee",
  siteUrl: "https://seokulee.github.io/",
  links: {
    github: "https://github.com/seokulee",
    linkedIn: "https://www.linkedin.com/in/seoku/",
    // facebook: "https://www.facebook.com",
    // twitter: "https://twitter.com",
    // x: "https://x.com",
    instagram: "https://www.instagram.com/ofseoku/",
    // medium: "https://medium.com",
    // blogger: "https://blogger.com",
    email: "mailto:cd1004s@gmail.com",
    // resume: "",
    // link: "",
  },
  useAbout: true,
  giscus: {
    repo: "seokulee/seokulee.github.io",
    repoId: "864517068",
    category: "Comments",
    categoryId: "DIC_kwDOFguqvs4ChwGy",
    mapping: "pathname",
    strict: "0",
    reactionsEnabled: "1",
    inputPosition: "bottom",
    lang: "en",
  },
}
